package tr.havelsan.kovan.apigen.common.enums;

public enum EnumModule {

    CONDITION,
    GENERAL,
    GENERAL_ADDRESS,
    INTEGRATIONS,
    ORGANIZATION,
    PARAMETERS,

    CONFIGURATION_MANAGEMENT,
    ENGINEERING,
    MAINTENANCE_ASSETS_MANAGEMENT,
    MAINTENANCE_REPAIR_APPLICATION,
    PREVENTIVE_MAINTENANCE,

    MATERIAL_IDENTIFICATION,
    PURCHASING,
    STOCK,
    WAREHOUSE,

    PRODUCTION_CUSTOMISATION,
    PRODUCTION_APPLICATION,

    QUALITY_CUSTOMISATION,
    QUALITY_APPLICATION;
}
